### ISSUE TITLE
Not an issue for this guide but for Codewars: your Haskell translation of common denominators

### ISSUE THREAD

**Issue by g964** [bkaestner/codewars-rules#4]
Very sorry to bother you here but one week ago I posted for you a message asking for a look from  you at the test of your Haskell translation of the kata "Common Denominators":
http://www.codewars.com/kata/common-denominators/discuss#55a8607820d11923ed000031
It seems that you didn't see it. Can you answer someone named "Smok"?
I don't know other way to communicate with you, seems you are not looking Codewars these days...

**Comment by bkaestner** [comment]
> I don't know other way...

Well, I don't get any notifications, since I didn't comment on the thread in the last 10 days. That being said, the reference solution is simply wrong. But I'm currently mobile and won't be able to fix it till Monday.

**Comment by bkaestner** [comment]
I 've posted a comment there, but again, I'm currently only on my tablet, so it's rather difficult to write something in the kata editor. 

If you want to fix it yourself: create the `gcd` of all ratios of the current solution, and divide everything by that number:

``` haskell
  let g = foldr (\(x,y) p -> gcd x y `gcd` p) 1 $ oldSolution
  in map (\(a,b) -> (a `div` g, b `div` g)) oldSolution
```

Keep in mind that I didn't check that solution. Feel free to remind me in this repository's or codewars.com's gitter.

**Comment by bkaestner** [comment]
Should be fixed now. I simply reduced every term in `forAll`.
