### ISSUE TITLE
Typo: "sentencens"

### ISSUE THREAD

**Issue by wouterduckaert** [bkaestner/codewars-rules#6]
Located in file _0100-General.md_ in the _rules_ folder.

I wasn't sure if I should open an issue for something as small as this, but I figured you might want to know.

**Comment by bkaestner** [comment]
Thanks! Feel free to create a pull-request for typos, as they are sometimes hard to locate in long documents.

On a sidenote, I should probably create an aspell script to check spelling before I commit.
